runtime: java
env: flex

# [START gae_flex_env_variables]
#env_variables:
#  JETTY_ARGS: -Djava.util.logging.config.file=WEB-INF/logging.properties
# [END gae_flex_env_variables]
runtime_config:
  server: tomcat8

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 50

env_variables:
  JAVA_USER_OPTS: '-Dspring.profiles.active=google'
  APP_ENCRYPTION_SECRET: 'itb_secret_2020'

manual_scaling:
  instances: 1

#automatic_scaling:
#  min_num_instances: 2
#  max_num_instances: 4
#  cool_down_period_sec: 180
#  cpu_utilization:
#    target_utilization: 0.7

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 120
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 1200

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 60
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1200
